name: rick_and_morty
description: rick and morty characters app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Service  locator
  get_it: ^7.2.0
  #BLoC for state router_management:
  flutter_bloc: ^8.0.1
  #Value equality
  equatable: ^2.0.3
  #Functional programming thingies
  dartz: ^0.10.1
  #Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

